name: Build and Push images to DockerHub

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build images with Docker Compose
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "../../docker-compose-build.yaml"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Tag each image
      - run: docker tag udagram-frontend:local ebukachuqz/udagram-frontend:v1
      - run: docker tag udagram-api-feed ebukachuqz/udagram-api-feed:v1
      - run: docker tag udagram-api-user ebukachuqz/udagram-api-user:v1
      - run: docker tag reverseproxy ebukachuqz/reverseproxy:v1

      # push images to DockerHub
      - run: docker push ebukachuqz/udagram-frontend:v1
      - run: docker push ebukachuqz/udagram-api-feed:v1
      - run: docker push ebukachuqz/udagram-api-user:v1
      - run: docker push ebukachuqz/reverseproxy:v1
